
label: topsurvey
namespace: topsurvey
name: topsurvey

  
deployment:
  image: 0000000000000.dkr.ecr.us-east-1.amazonaws.com/applications/topsurvey:latest
  containerPort: 80
  resources:
    limits:
      cpu: 256m
      memory: 150Mi
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  name: topsurvey
  path: /


hpa:
  maxReplicas: 20
  minReplicas: 1
  averageValue: 128Mi